name: Publish to GH Pages
on: 
  pull_request:
      branches: [ "main" ]
      
  jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - name: 
        run: |
          echo The PR was merged
          yarn run deploy





  # merge to main, run 'run deploy' and set 